### ISSUE TITLE
Create certificates for IgG SARS-CoV-2 (Antibodies) test

### ISSUE THREAD

**Issue by fulldecent** [Genobank/genobankio-js#25]
Considering this taxonomy

```json
"5": {
  "internationalName": "COVID-19-IGG",
  "descriptionLocalizations": {
    "en": "COVID-19 IgG antibody test was administered",
    "es": "Se administró la prueba de anticuerpos IgG COVID-19",
    "pt": "O teste de anticorpos COVID-19 IgG foi administrado",
    "zh": "进行了 COVID-19 IgG 抗体测试"
  },
  "resultsTaxonomy": {
    "resultsTaxonomy": {
      "N": {
        "internationalName": "NEGATIVE",
        "descriptionLocalizations": {
          "en": "SARS-CoV-2 was not detected",
          "es": "SARS-CoV-2 no se detectó",
          "pt": "SARS-CoV-2 não foi detectado",
          "zh": "未检测到SARS-CoV-2"
        }
      },
      "P": {
        "internationalName": "POSITIVE",
        "descriptionLocalizations": {
          "en": "SARS-CoV-2 was detected",
          "es": "SARS-CoV-2 se detectó",
          "pt": "SARS-CoV-2 foi detectado",
          "zh": "检测到SARS-CoV-2"
        }
      }
    }
  }
}
```

---

Related https://github.com/Genobank/genobank.io/issues/292

# Work plan

https://github.com/Genobank/genobankio-js#release-process

**Comment by fulldecent** [comment]
@duribebe please confirm translations here ^^

**Comment by duribebe** [comment]
"5": {
  "internationalName": "COVID-19-IGG",
  "descriptionLocalizations": {
    "en": "COVID-19 IgG antibody test was administered",
    "es": "Se administró la prueba de anticuerpos IgG COVID-19",
    "pt": "O teste de anticorpos COVID-19 IgG foi administrado",
    "zh": "进行了 COVID-19 IgG 抗体测试"
  },
  "resultsTaxonomy": {
    "resultsTaxonomy": {
      "N": {
        "internationalName": "NEGATIVE",
        "descriptionLocalizations": {
          "en": "IgG SARS-CoV-2 not detected",
          "es": "IgG SARS-CoV-2 no se detectó",
          "pt": "IgG SARS-CoV-2 não foi detectado",
          "zh": "未检测到SARS-CoV-2"
        }
      },
      "P": {
        "internationalName": "POSITIVE",
        "descriptionLocalizations": {
          "en": "IgG SARS-CoV-2 was detected >15 UA/mL",
          "es": "IgG SARS-CoV-2 se detectó >15 UA/mL",
          "pt": "IgG SARS-CoV-2 foi detectado >15 UA/mL",
          "zh": "检测到SARS-CoV-2"
        }
      }

**Comment by duribebe** [comment]
Ready Thanks!

**Comment by fulldecent** [comment]
Prioritized. @MoMannn Please proceed with this.

**Comment by MoMannn** [comment]
@fulldecent 

https://github.com/Genobank/genobankio-js/pull/26

Scheduled for website release 4: https://github.com/Genobank/genobank.io/issues/374
