### ISSUE TITLE
Improve error messages

### ISSUE THREAD

**Issue by fulldecent** [Genobank/genobankio-js#31]
Please implement these behaviors:

- If less arguments are passed than the number of required arguments, show an error
- If the time is obviously attempting to use UNIX seconds instead of UNIX milliseconds, show an error

**Comment by MoMannn** [comment]
As a second point where are you getting this problem? 

In typescript it is defined as date format and you cannot input anything else then date. 
Is this a problem in CLI?

**Comment by fulldecent** [comment]
Here is a test case where I passed in the Java parameters and it did not work and it did not explain why it did not work

![Screen Shot 2021-09-09 at 20 18 16](https://user-images.githubusercontent.com/382183/132778947-1da89e68-21f0-4e84-bfad-1f84660bb499.png)
![Screen Shot 2021-09-09 at 20 18 18](https://user-images.githubusercontent.com/382183/132778956-03281f36-4d05-45f1-9789-72216ab93405.png)

**Comment by fulldecent** [comment]
Please ensure this example works : https://github.com/Genobank/genobank.io/wiki/Test-Accounts-and-Certificates

and also update that text to say "Java / JS example"

**Comment by MoMannn** [comment]
Add javascript example to wiki

**Comment by MoMannn** [comment]
https://github.com/Genobank/genobank.io/wiki/Test-Accounts-and-Certificates
