### ISSUE TITLE
Valid certificate is not accepted

### ISSUE THREAD

**Issue by fulldecent** [Genobank/genobankio-js#33]
The Java application was used to create a VACCINE certificate. But it was not accepted by the front-end website.

---

❯ java -jar target/*.jar --test 'wrong outside clever wagon father insane boy junk punch duck drift cupboard' 41 'Daniel Uribe' 'DOB 1976-02-19' '4' 'C' 'DOSE 1 MODERNA 2021-03-25 DOSE 2 MODERNA 2021-04-22' 1614069145429

Blockchain Lab Results Certification
Java Certification Example, version 1.0
(c) GenoBank.io 🧬

Network:     TEST NETWORK
Address:     0x13E541de78DaCC48722aD4F4E9903E501b233706
Patient:     Daniel Uribe
Passport:    DOB 1976-02-19
Procedure:   4
Result:      C
Serial:      DOSE 1 MODERNA 2021-03-25 DOSE 2 MODERNA 2021-04-22
Time:        1614069145429
Signature:   0xbb992a77f297cf05a8af307abb7be1a3b4e4d0686b6027a325dbdc9c8210a4f25aa97727f2a796bf1de0e3574a5ed71bb19a71de8bc8725d8e6594309a2cfc921b

Notarizing on blockchain...

Certificate URL
https://genobank.io/test/certificates/verify-certificate-v1#Daniel%20Uribe%7CDOB%201976-02-19%7C4%7CC%7CDOSE%201%20MODERNA%202021-03-25%20DOSE%202%20MODERNA%202021-04-22%7C1614069145429%7C41%7C0xbb992a77f297cf05a8af307abb7be1a3b4e4d0686b6027a325dbdc9c8210a4f25aa97727f2a796bf1de0e3574a5ed71bb19a71de8bc8725d8e6594309a2cfc921b%7C1631233601023%7C0x9b1f9da077a160bedf79a085e6a2fea861ebb83452560f4157c3ac61839492f879224876c12d874bdc0efeecb5694782b42d7c4cbb39d6840569200b261df4171c%7C0x37e214f586a1db2654b5becf8f23e6fadac7c9481fc2a9746459754f9934a7e7

**Comment by MoMannn** [comment]
Wrong taxonomy not reverted on testnet. Resolving first thing monday.
